export const PHONE_LOADED = 'PHONE_LOADED'
export const ADD_PRICE = 'ADD_PRICE'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const CHANGE_LOADING = 'LOADING'
export const CHANGE_ERROR = 'ERROR'
export const DELETE_CART_ITEM = 'DELETE_CART'
export const CHANGE_MODAL = 'CHANGE_MODAL'
export const UPDATE_COUNT = 'UPDATE_COUNT'
